# Generated by Django 3.1.1 on 2020-09-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=250)),
                ('Last_name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Age', models.IntegerField()),
                ('Income', models.IntegerField()),
            ],
        ),
    ]
